// 'use client'

import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import ToastProvider from '@/components/ToastProvider'
import JWTProvider from '@/components/JWTProvider'
// import { NextUIProvider } from '@nextui-org/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <JWTProvider>
          {/* <NextUIProvider> */}
            <ToastProvider>
              {children}
            </ToastProvider>
          {/* </NextUIProvider> */}
        </JWTProvider>
      </body>
    </html>
  )
}
